# Generated by Django 4.2.11 on 2024-03-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_treatment_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
